### ISSUE TITLE
Errors After Upgrade to 0.14.2

### ISSUE THREAD

**Issue by pakkle** [generic-ui/generic-ui#32]
After upgrade to 0.14.2 I got the following error:

Error: node_modules/@generic-ui/ngx-grid/structure/vertical-formation/core/domain/set-row-height/set-row-height.command-handler.d.ts:5:22 - error TS2420: Class 'SetRowHeightCommandHandler' incorrectly implements interface 'CommandHandler<StructureAggregate, SetRowHeightCommand>'.
  Type 'SetRowHeightCommandHandler' is missing the following properties from type 'CommandHandler<StructureAggregate, SetRowHeightCommand>': publishDomainEvents, handleAggregate

Is there something missing?

**Comment by generic-ui** [comment]
Can you please be more specific regarding reproducing this error ?

**Comment by pakkle** [comment]
I run

npm update @generic-ui/ngx-grid
npm update @generic-ui/fabric

and then

ng serve --host localhost --configuration=debug --port 8080

I got a lot of errors like above al related to various handlers. The very first error was:

Error: node_modules/@generic-ui/ngx-grid/composition/core/domain/column/move/left/composition.move-left-column.command-handler.d.ts:7:22 - error TS2420: Class 'CompositionMoveLeftColumnCommandHandler' incorrectly implements interface 'CommandHandler<CompositionAggregate, CompositionMoveLeftColumnCommand>'.
  Type 'CompositionMoveLeftColumnCommandHandler' is missing the following properties from type 'CommandHandler<CompositionAggregate, CompositionMoveLeftColumnCommand>': publishDomainEvents, handleAggregate

7 export declare class CompositionMoveLeftColumnCommandHandler implements CommandHandler<CompositionAggregate, CompositionMoveLeftColumnCommand> {

**Comment by generic-ui** [comment]
Have you also updated the @generic-ui/hermes library to the version 0.14.2 ?

**Comment by pakkle** [comment]
It was unclear that all the components should be upgraded. Closing the issue.
Thank you for quick response!
